### ISSUE TITLE
const { subtle } = require('crypto').webcrypto;

### ISSUE THREAD

**Issue by jimmywarting** [alastaircoote/webpush-webcrypto#1]
node has web crypto...
think that should be suggested/mentioned in the readme...

```js
import { webcrypto: crypto } from 'node:crypto'
```
Also think you should add some syntax highlight...
```
```js
```

**Comment by alastaircoote** [comment]
I do already mention Node in the "Bring your own webcrypto" section of the readme. Good call on the syntax highlighting though! I've added it.

**Comment by jimmywarting** [comment]
Ah, didn't spot the `xyz.webcrypto` at the end of the script. 
only read that you imported the hole node crypto module from the import statment
